### ISSUE TITLE
There is no script

### ISSUE THREAD

**Issue by robertpi** [jbara2002/WMIC-in-Windows-11#1]

**Comment by ionuttbara** [comment]
Yes. It is. Run only the .exe file in "Releases" Section. After that, run in cmd "wmic".
![image](https://user-images.githubusercontent.com/76656855/146670031-657191e5-101a-442a-8218-42d6462a6c26.png)

**Comment by ionuttbara** [comment]
![image](https://user-images.githubusercontent.com/76656855/146670066-5ffb71b7-4d4e-4b49-8e23-180c45ebb6c3.png)
